import { STRATEGIC_V4_PROMPTS } from "./strategic-v4-prompts";

export type BuiltinPrompt = {
  id: string;
  title: string;
  category: string;
  content: string;
};

export const BUILTIN_PROMPTS: BuiltinPrompt[] = [
  // Architecte d'interieur
  { id: "archi-01", category: "architecte-interieur", title: "Premier contact client", content: "Tu es un architecte d'interieur specialise en renovation residentielle haut de gamme. Redige un email de premier contact suite a une demande de renovation d'un appartement de [surface]m2 a [ville]. Le prospect a trouve mon contact via [source]. L'email doit faire 8 lignes, avoir un ton elegant et rassurant, et inclure une invitation a un rendez-vous decouverte." },
  { id: "archi-02", category: "architecte-interieur", title: "Proposition commerciale", content: "Tu es un expert en redaction commerciale pour les architectes d'interieur independants. Redige une proposition commerciale d'une page pour une mission de [type de projet] d'un budget estime de [budget]. Inclus : accroche, description de la mission, livrables, methodologie, tarif et appel a l'action. Ton professionnel et oriente resultats." },
  { id: "archi-03", category: "architecte-interieur", title: "Bilan de chantier", content: "Tu es un architecte d'interieur specialise en gestion de projet. Redige un email de bilan de chantier a mi-parcours pour un client [profil client]. Avancement : [X]%. Points resolus : [liste]. Points en cours : [liste]. Ton rassurant et structure. 10 lignes maximum." },
  { id: "archi-04", category: "architecte-interieur", title: "Reponse a un retard", content: "Tu es un expert en communication client pour les prestataires de service. Redige un email pour annoncer un retard de [duree] sur un projet de renovation du a [raison]. Le message doit valoriser l'avancement, expliquer le retard sans s'excuser excessivement, et proposer un nouveau planning. Ton transparent et professionnel." },
  { id: "archi-05", category: "architecte-interieur", title: "Presentation d'une realisation", content: "Tu es un expert en personal branding pour les architectes d'interieur. Redige un post LinkedIn de 200 mots pour presenter la livraison d'un projet de [type]. Inclus : contexte du projet, contraintes surmontees, resultat final, et une question engageante pour l'audience. Ton expert mais accessible." },
  { id: "archi-06", category: "architecte-interieur", title: "FAQ site web", content: "Tu es un expert en experience client pour les architectes d'interieur independants. Genere une FAQ de 8 questions-reponses que les prospects posent avant de prendre contact. Les reponses doivent etre rassurantes, claires et donner envie de passer a l'action." },
  { id: "archi-07", category: "architecte-interieur", title: "Relance prospect", content: "Tu es un expert en communication commerciale. Redige un email de relance pour un prospect qui a demande un devis il y a [X] jours sans donner de retour. 5 lignes maximum. Ton naturel et non commercial. Laisser une porte ouverte sans mettre de pression." },
  { id: "archi-08", category: "architecte-interieur", title: "Description de prestation", content: "Tu es un expert en copywriting pour les metiers creatifs. Redige une description de 100 mots pour la prestation [nom de la prestation] d'un cabinet d'architecture d'interieur. La description doit mettre en avant les benefices pour le client, pas les caracteristiques techniques. Ton elegant et inspirant." },
  { id: "archi-09", category: "architecte-interieur", title: "Annonce hausse de tarifs", content: "Tu es un expert en communication client. Redige un email pour annoncer une revision tarifaire de [X]% applicable a partir du [date] a mes clients fideles. Le message doit valoriser la relation, expliquer la revision sans s'excuser, et avoir un ton respectueux et transparent." },
  { id: "archi-10", category: "architecte-interieur", title: "Demande de temoignage", content: "Tu es un expert en marketing pour les independants. Redige 3 versions d'une demande de temoignage a envoyer a un client satisfait apres livraison d'un projet. Les versions doivent etre courtes, naturelles, et faciliter la redaction pour le client en lui suggerant des axes de reponse." },

  // Plombier independant
  { id: "plombier-11", category: "plombier-independant", title: "Devis rapide", content: "Tu es un expert en communication commerciale pour les artisans independants. Redige un email d'accompagnement de devis pour une intervention de [type de travaux] chez un particulier. Montant : [X]EUR. Le message doit etre court (5 lignes), rassurer sur la qualite, et inclure une date de validite du devis." },
  { id: "plombier-12", category: "plombier-independant", title: "Confirmation d'intervention", content: "Tu es un expert en relation client pour les artisans. Redige un SMS de confirmation d'intervention pour [type d'intervention] prevu le [date] a [heure]. Le message doit faire 3 lignes, inclure le rappel de l'adresse et un numero de contact en cas d'imprevu." },
  { id: "plombier-13", category: "plombier-independant", title: "Reponse urgence", content: "Tu es un expert en communication pour les artisans de depannage. Redige un message de reponse a une demande d'urgence pour [type de panne] recue a [heure]. Le message doit confirmer la prise en charge, donner un delai d'intervention estime, et rassurer le client. 4 lignes maximum." },
  { id: "plombier-14", category: "plombier-independant", title: "Relance devis sans reponse", content: "Tu es un expert en communication commerciale pour les artisans. Redige un SMS de relance pour un client qui n'a pas repondu a un devis de [X]EUR envoye il y a [Y] jours. Ton naturel, sans pression. 2 lignes maximum." },
  { id: "plombier-15", category: "plombier-independant", title: "Reponse avis negatif", content: "Tu es un expert en gestion de reputation pour les artisans independants. Redige une reponse a cet avis Google negatif : [colle l'avis]. 5 lignes maximum. Reconnaitre l'insatisfaction sans admettre une faute, proposer une solution, ton calme et professionnel." },
  { id: "plombier-16", category: "plombier-independant", title: "Presentation sur reseaux", content: "Tu es un expert en communication digitale pour les artisans. Redige un post Facebook de 150 mots pour presenter mon activite de plomberie independante a [ville]. Mets en avant la reactivite, le serieux et la proximite. Inclus un appel a l'action pour demander un devis." },
  { id: "plombier-17", category: "plombier-independant", title: "Message suivi apres intervention", content: "Tu es un expert en relation client pour les artisans. Redige un SMS de suivi envoye 48h apres une intervention de [type]. Le message doit s'assurer de la satisfaction, proposer de noter sur Google, et rester chaleureux. 3 lignes maximum." },
  { id: "plombier-18", category: "plombier-independant", title: "Annonce disponibilites", content: "Tu es un expert en communication locale pour les artisans independants. Redige un post Facebook pour annoncer des disponibilites en [mois] pour des interventions de [type de travaux] sur le secteur de [zone geographique]. Ton direct et accessible. 100 mots maximum." },
  { id: "plombier-19", category: "plombier-independant", title: "Conditions generales", content: "Tu es un expert juridique pour les artisans independants francais. Redige des conditions generales d'intervention simples et claires pour un plombier independant. Inclus : modalites de paiement, deplacements, urgences, garantie sur les travaux, politique d'annulation. Langage accessible." },
  { id: "plombier-20", category: "plombier-independant", title: "Demande de recommandation", content: "Tu es un expert en marketing pour les artisans. Redige un message a envoyer a un client satisfait pour lui demander de parler de mes services a son entourage. Ton chaleureux et naturel. Propose-lui de mentionner [specialite] et [zone]. 4 lignes maximum." },

  // Entrepreneur independant (Cinemark Azur)
  { id: "cine-21", category: "entrepreneur-independant", title: "Presentation de l'agence", content: "Tu es un expert en copywriting pour les agences creatives independantes. Redige une presentation de 200 mots de Cinemark Azur, agence de placement de produits regionaux dans les productions cinematographiques independantes en region PACA. Public cible : directeurs marketing de marques locales. Ton professionnel et inspirant." },
  { id: "cine-22", category: "entrepreneur-independant", title: "Email de prospection marque", content: "Tu es un expert en developpement commercial pour les agences creatives. Redige un email de prospection pour contacter le directeur marketing d'une marque [secteur] basee en PACA, pour lui proposer un placement de produit dans une production cinematographique independante. Ton direct et differenciant. 10 lignes maximum." },
  { id: "cine-23", category: "entrepreneur-independant", title: "Proposition de partenariat", content: "Tu es un expert en redaction commerciale pour les agences de communication. Redige une proposition de partenariat d'une page pour integrer la marque [nom] dans la production [titre]. Inclus : contexte de la production, audience cible, modalites du placement, valeur pour la marque, tarif et prochaines etapes." },
  { id: "cine-24", category: "entrepreneur-independant", title: "Pitch deck resume", content: "Tu es un expert en storytelling pour les pitchs commerciaux. Redige le script d'un pitch de 3 minutes pour presenter Cinemark Azur a un directeur marketing. Structure : probleme / solution / preuve / offre / appel a l'action. Ton confiant et memorable." },
  { id: "cine-25", category: "entrepreneur-independant", title: "Post LinkedIn positionnement", content: "Tu es un expert en personal branding LinkedIn pour les entrepreneurs creatifs. Redige un post de 200 mots sur le sujet suivant : pourquoi le placement de produit dans le cinema independant est une opportunite sous-exploitee par les marques regionales. Ton expert, accroche forte, question finale engageante." },
  { id: "cine-26", category: "entrepreneur-independant", title: "Email suivi apres rencontre", content: "Tu es un expert en communication commerciale. Redige un email de suivi a envoyer 24h apres une premiere rencontre avec un prospect interesse par les services de Cinemark Azur. Le message doit reformuler les points cles discutes, apporter un element de valeur supplementaire, et proposer une prochaine etape concrete." },
  { id: "cine-27", category: "entrepreneur-independant", title: "Reponse a une objection budget", content: "Tu es un expert en negociation commerciale pour les agences creatives. Redige une reponse par email a un prospect qui dit que le budget de placement de produit est trop eleve. Le message doit comprendre l'objection, repositionner la valeur, et proposer une alternative accessible. Ton comprehensif et convaincant." },
  { id: "cine-28", category: "entrepreneur-independant", title: "Communique de presse", content: "Tu es un expert en relations presse pour les acteurs culturels independants. Redige un communique de presse d'une page annoncant le partenariat entre Cinemark Azur et [marque/production]. Inclus : accroche, contexte, citations fictives des deux parties, et informations de contact." },
  { id: "cine-29", category: "entrepreneur-independant", title: "Presentation partenaires producteurs", content: "Tu es un expert en communication pour les intermediaires du secteur cinematographique. Redige un email de presentation de Cinemark Azur a destination d'un producteur de films independants en PACA. Mets en avant la valeur apportee a la production (financement partiel, ancrage regional, credibilite locale). 10 lignes." },
  { id: "cine-30", category: "entrepreneur-independant", title: "Fiche offre commerciale", content: "Tu es un expert en copywriting commercial. Redige une fiche offre d'une page pour le service de placement de produit de Cinemark Azur. Structure : titre accrocheur, probleme client, solution, ce qui est inclus, resultats attendus, tarif indicatif, appel a l'action. Ton professionnel et differenciant." },

  // Jardinier independant
  { id: "jardinier-31", category: "jardinier-independant", title: "Devis entretien annuel", content: "Tu es un expert en communication commerciale pour les artisans paysagistes. Redige un email d'accompagnement de devis pour un contrat d'entretien annuel de jardin chez un particulier. Surface : [X]m2. Frequence : [Y] fois par mois. Le message doit rassurer sur le serieux, detailler les prestations incluses, et inclure une invitation a valider. 8 lignes." },
  { id: "jardinier-32", category: "jardinier-independant", title: "Presentation saisonniere", content: "Tu es un expert en communication locale pour les jardiniers independants. Redige un post Facebook pour annoncer le demarrage de la saison [printemps/automne] et les prestations disponibles sur le secteur de [zone]. Ton chaleureux et proche. 120 mots maximum avec appel a l'action." },
  { id: "jardinier-33", category: "jardinier-independant", title: "Conseil client personnalise", content: "Tu es un expert horticole specialise en jardins mediterraneens. Redige un message de conseil personnalise pour un client dont le jardin de [X]m2 est expose [orientation] a [ville]. Propose 3 actions prioritaires pour [saison]. Ton pedagogique et accessible. 10 lignes." },
  { id: "jardinier-34", category: "jardinier-independant", title: "Suivi apres intervention", content: "Tu es un expert en relation client pour les artisans du jardin. Redige un SMS envoye le soir meme apres une intervention d'entretien chez un client fidele. Le message doit resumer ce qui a ete fait, mentionner un point d'attention pour la prochaine visite, et rester chaleureux. 3 lignes." },
  { id: "jardinier-35", category: "jardinier-independant", title: "Reponse urgence climatique", content: "Tu es un expert en communication pour les jardiniers professionnels. Redige un message a envoyer a tous mes clients apres un episode meteo exceptionnel (gel, secheresse, tempete) pour leur proposer une visite de controle. Ton proactif et rassurant. 5 lignes." },
  { id: "jardinier-36", category: "jardinier-independant", title: "Presentation nouvelle prestation", content: "Tu es un expert en marketing pour les artisans independants. Redige un email pour annoncer a mes clients existants une nouvelle prestation de [type : installation arrosage automatique / creation potager / taille haie speciale]. Le message doit expliquer le benefice, donner un prix indicatif, et inclure un appel a l'action. 8 lignes." },
  { id: "jardinier-37", category: "jardinier-independant", title: "Post realisation avant/apres", content: "Tu es un expert en communication visuelle pour les paysagistes. Redige une legende Instagram de 100 mots pour accompagner des photos avant/apres d'une transformation de jardin a [ville]. Type de jardin : [description]. Accroche forte, description du travail realise, hashtags pertinents." },
  { id: "jardinier-38", category: "jardinier-independant", title: "Relance client inactif", content: "Tu es un expert en fidelisation client pour les artisans. Redige un SMS pour relancer un client qui n'a pas fait appel a mes services depuis [X] mois. Ton chaleureux et naturel. Propose une visite de diagnostic offerte. 3 lignes maximum." },
  { id: "jardinier-39", category: "jardinier-independant", title: "Conditions generales", content: "Tu es un expert juridique pour les artisans independants francais. Redige des conditions generales d'intervention simples pour un jardinier independant. Inclus : devis et acceptation, modalites de paiement, annulation, intemperies, responsabilite. Langage clair et accessible." },
  { id: "jardinier-40", category: "jardinier-independant", title: "Guide entretien saisonnier", content: "Tu es un expert horticole specialise en jardins de particuliers en region [PACA/Normandie/etc.]. Redige un guide pratique de 300 mots sur les 5 gestes indispensables pour preparer son jardin pour [saison]. Ton pedagogique, accessible, et enthousiaste." },

  // Artiste sculpteur (EZEA)
  { id: "ezea-41", category: "artiste-sculpteur", title: "Presentation de l'artiste", content: "Tu es un expert en redaction editoriale pour les artistes contemporains. Redige une biographie de 200 mots pour un artiste sculpteur specialise dans les sculptures en resine avec incrustations de street art, base sur la Cote d'Azur. Marque : EZEA. Ton artistique, memorable et differenciant." },
  { id: "ezea-42", category: "artiste-sculpteur", title: "Description d'une oeuvre", content: "Tu es un expert en critique d'art contemporain. Redige une description de 150 mots pour la sculpture suivante : [titre, materiaux, dimensions, concept]. La description doit evoquer l'intention artistique, les materiaux, l'emotion recherchee, et la valeur pour le collectionneur. Ton poetique et precis." },
  { id: "ezea-43", category: "artiste-sculpteur", title: "Email galerie", content: "Tu es un expert en developpement commercial pour les artistes independants. Redige un email de prospection pour proposer une collaboration a une galerie d'art contemporain [ville]. Presente EZEA en 3 phrases, mentionne le concept unique resine/street art, et propose une rencontre. 8 lignes. Ton confiant et artistique." },
  { id: "ezea-44", category: "artiste-sculpteur", title: "Post Instagram oeuvre", content: "Tu es un expert en communication digitale pour les artistes visuels. Redige une legende Instagram de 100 mots pour presenter une nouvelle sculpture [description]. Inclus : intention artistique, materiaux utilises, disponibilite, prix indicatif ou mention 'sur demande', et 8 hashtags pertinents art contemporain." },
  { id: "ezea-45", category: "artiste-sculpteur", title: "Proposition art investissement", content: "Tu es un expert en art comme investissement. Redige un email a destination d'un investisseur ou collectionneur pour presenter l'interet d'acquerir une oeuvre EZEA. Mets en avant : unicite des pieces, positionnement marche, potentiel de valorisation, et lien entre street art et art contemporain. Ton expert et convaincant." },
  { id: "ezea-46", category: "artiste-sculpteur", title: "Dossier de presse", content: "Tu es un expert en relations presse pour les artistes contemporains. Redige un dossier de presse d'une page pour EZEA, marque de sculptures en resine a incrustation street art. Inclus : presentation de l'artiste, concept, materiaux et technique, oeuvres phares, expositions, contact. Ton editorial et memorable." },
  { id: "ezea-47", category: "artiste-sculpteur", title: "Reponse demande de prix", content: "Tu es un expert en vente d'art pour les artistes independants. Redige une reponse email a un particulier qui demande le prix d'une sculpture EZEA visible sur Instagram. Le message doit valoriser l'oeuvre avant d'annoncer le tarif, expliquer ce qui justifie le prix, et proposer une rencontre ou un appel. Ton chaleureux et professionnel." },
  { id: "ezea-48", category: "artiste-sculpteur", title: "Collaboration brand", content: "Tu es un expert en developpement de partenariats pour les artistes contemporains. Redige un email pour proposer une collaboration artistique entre EZEA et une marque de luxe ou premium [secteur]. Mets en avant la coherence des univers, les formats de collaboration possibles (oeuvre exclusive, edition limitee, activation evenementielle), et propose une rencontre." },
  { id: "ezea-49", category: "artiste-sculpteur", title: "Presentation exposition", content: "Tu es un expert en communication evenementielle pour le monde de l'art. Redige un texte de presentation de 200 mots pour une exposition EZEA dans un lieu [galerie/hotel/espace evenementiel]. Inclus : titre de l'exposition, concept, oeuvres presentees, date et lieu. Ton poetique et invitant." },
  { id: "ezea-50", category: "artiste-sculpteur", title: "Story Instagram coulisses atelier", content: "Tu es un expert en storytelling pour les artistes visuels sur Instagram. Redige le texte pour une serie de 5 stories montrant les coulisses de la creation d'une sculpture EZEA. Chaque story doit avoir une legende courte (15 mots max) et une accroche qui donne envie de voir la suite." },

  // Coiffeur independant
  { id: "coiffure-01", category: "coiffeur-independant", title: "Confirmation de rendez-vous", content: "Tu es un expert en relation client pour les salons de coiffure independants. Redige un SMS de confirmation de rendez-vous pour [prenom client] prevu le [date] a [heure] pour une prestation [type]. Le message doit faire 3 lignes, inclure l'adresse et proposer d'annuler si besoin. Ton chaleureux et professionnel." },
  { id: "coiffure-02", category: "coiffeur-independant", title: "Relance client inactif", content: "Tu es un expert en fidelisation client pour les salons de coiffure. Redige un SMS pour relancer une cliente qui n'est pas revenue depuis [X] mois. Le message doit etre chaleureux, non intrusif, et inclure une offre de bienvenue. 3 lignes maximum. Ton naturel et sincere." },
  { id: "coiffure-03", category: "coiffeur-independant", title: "Lancement d'une nouvelle prestation", content: "Tu es un expert en communication digitale pour les salons de coiffure independants. Redige un post Instagram pour annoncer le lancement de la prestation [nom de la prestation] a [tarif]. Ma clientele est [profil]. Le post doit faire 5 lignes, avoir un ton enthousiaste, et inclure 5 hashtags pertinents." },
  { id: "coiffure-04", category: "coiffeur-independant", title: "Reponse a un avis negatif", content: "Tu es un expert en gestion de reputation pour les independants. Redige une reponse a cet avis Google : [colle l'avis]. 5 lignes maximum. Reconnaitre l'insatisfaction sans admettre une faute, proposer une solution concrete, ton professionnel et calme." },
  { id: "coiffure-05", category: "coiffeur-independant", title: "Legende avant/apres transformation", content: "Tu es un expert en personal branding pour les coiffeurs independants. Redige une legende Instagram de 100 mots pour accompagner des photos avant/apres d'une transformation [type : coupe / couleur / soin]. Accroche forte, description du travail realise, appel a la prise de rendez-vous, 6 hashtags." },
  { id: "coiffure-06", category: "coiffeur-independant", title: "Annonce hausse de tarifs", content: "Tu es un expert en communication client pour les artisans independants. Redige un message a envoyer a mes clientes fideles pour annoncer une revision tarifaire de [X]% applicable le [date]. Ton transparent et respectueux, valoriser la relation sans s'excuser. 8 lignes maximum." },
  { id: "coiffure-07", category: "coiffeur-independant", title: "Description de la carte des soins", content: "Tu es un expert en copywriting pour les salons de coiffure. Redige une description de 80 mots pour chacune de ces prestations : [liste des prestations]. Chaque description doit mettre en avant le benefice pour la cliente et donner envie de reserver. Ton elegant et accessible." },
  { id: "coiffure-08", category: "coiffeur-independant", title: "Annonce programme fidelite", content: "Tu es un expert en marketing pour les salons de coiffure independants. Redige un message pour annoncer le lancement d'un programme fidelite : [decris les avantages]. Le message doit etre envoye par SMS a mes clientes existantes, faire 4 lignes, et avoir un ton enthousiaste et exclusif." },
  { id: "coiffure-09", category: "coiffeur-independant", title: "Story Instagram coulisses salon", content: "Tu es un expert en storytelling pour les artisans sur Instagram. Redige le texte de 5 stories montrant une journee dans mon salon de coiffure. Chaque story a une legende de 10 mots max et une accroche qui donne envie de voir la suivante. Ton authentique et chaleureux." },
  { id: "coiffure-10", category: "coiffeur-independant", title: "Message rappel no-show", content: "Tu es un expert en communication client pour les independants. Redige un SMS a envoyer a un client qui n'est pas venu a son rendez-vous sans prevenir. Le message doit etre ferme mais courtois, rappeler la politique d'annulation, et proposer de replanifier. 3 lignes." },

  // Traiteur evenementiel
  { id: "traiteur-11", category: "traiteur-evenementiel", title: "Reponse a une demande de devis", content: "Tu es un expert en communication commerciale pour les traiteurs evenementiels haut de gamme. Redige un email de reponse a une demande de devis pour un [type d'evenement] de [nombre] personnes prevu le [date] a [lieu]. Le message doit qualifier les besoins, presenter notre approche, et inviter a un appel decouverte. Ton professionnel et chaleureux. 10 lignes." },
  { id: "traiteur-12", category: "traiteur-evenementiel", title: "Confirmation de prestation", content: "Tu es un expert en relation client pour les traiteurs evenementiels. Redige un email de confirmation de prestation pour [prenom client] pour un [type d'evenement] de [nombre] personnes le [date]. Recapitulatif du menu valide, prochaines etapes, coordonnees. Ton rassurant et professionnel." },
  { id: "traiteur-13", category: "traiteur-evenementiel", title: "Gestion d'une annulation", content: "Tu es un expert en communication client pour les prestataires evenementiels. Redige un email de reponse a une annulation de prestation [nombre de jours] avant l'evenement. Appliquer les conditions d'annulation sans agressivite, proposer une reprogrammation avec geste commercial. Ton professionnel et comprehensif." },
  { id: "traiteur-14", category: "traiteur-evenementiel", title: "Description menu saisonnier", content: "Tu es un expert en copywriting gastronomique. Redige une description de menu de [saison] pour un traiteur evenementiel haut de gamme. [Liste les plats]. Chaque plat doit avoir une description poetique de 2 lignes mettant en valeur les produits et l'origine. Ton elegant et gourmand." },
  { id: "traiteur-15", category: "traiteur-evenementiel", title: "Post reseaux apres evenement", content: "Tu es un expert en communication digitale pour les traiteurs evenementiels. Redige un post LinkedIn de 200 mots pour presenter la reussite d'un [type d'evenement] de [nombre] personnes. Mettre en avant : le defi releve, les choix gastronomiques, la satisfaction client. Ton expert mais accessible." },
  { id: "traiteur-16", category: "traiteur-evenementiel", title: "Prospection entreprises", content: "Tu es un expert en developpement commercial B2B pour les traiteurs evenementiels. Redige un email de prospection pour contacter le responsable des evenements d'une entreprise [secteur] afin de proposer nos services pour leurs prochains [type d'evenements]. Ton direct et differenciant. 10 lignes." },
  { id: "traiteur-17", category: "traiteur-evenementiel", title: "Reponse a une objection prix", content: "Tu es un expert en negociation commerciale pour les prestataires evenementiels haut de gamme. Redige un email de reponse a un prospect qui trouve notre devis trop eleve. Revaloriser la proposition sans baisser le prix, proposer une alternative adaptee au budget. Ton comprehensif et professionnel." },
  { id: "traiteur-18", category: "traiteur-evenementiel", title: "Demande de temoignage post-evenement", content: "Tu es un expert en marketing pour les prestataires evenementiels. Redige 3 versions d'un message a envoyer a un client satisfait 48h apres l'evenement pour lui demander un temoignage. Versions : SMS / email / LinkedIn. Court, naturel, avec axes de reponse suggeres." },
  { id: "traiteur-19", category: "traiteur-evenementiel", title: "Description des formules", content: "Tu es un expert en copywriting commercial pour la gastronomie evenementielle. Redige une description de 120 mots pour chacune de ces formules : [liste des formules et prix]. Chaque description doit mettre en avant les benefices pour le client, l'occasion adaptee, et donner envie de reserver. Ton elegant et appetissant." },
  { id: "traiteur-20", category: "traiteur-evenementiel", title: "Annonce disponibilites saisonnieres", content: "Tu es un expert en communication pour les traiteurs evenementiels. Redige un post LinkedIn pour annoncer nos disponibilites pour la saison [printemps/ete/automne/hiver] et les types d'evenements que nous accompagnons. Inclure un appel a l'action pour reserver une consultation. 150 mots. Ton professionnel et inspirant." },

  // Chef a domicile
  { id: "chefdom-21", category: "chef-a-domicile", title: "Presentation de l'offre", content: "Tu es un expert en copywriting pour les chefs cuisiniers a domicile. Redige une presentation de 200 mots pour mon activite de chef a domicile. Specialite : [cuisine]. Zone : [ville/region]. Occasions couvertes : [diners prives / anniversaires / etc.]. Public cible : [profil client]. Ton elegant, inspirant et rassurant." },
  { id: "chefdom-22", category: "chef-a-domicile", title: "Proposition diner prive", content: "Tu es un expert en communication commerciale pour les chefs a domicile haut de gamme. Redige une proposition commerciale d'une page pour un diner prive de [nombre] personnes le [date]. Menu propose : [liste]. Inclus : deroule de la soiree, ce qui est compris dans la prestation, tarif, et conditions. Ton raffine et professionnel." },
  { id: "chefdom-23", category: "chef-a-domicile", title: "Email suivi post-prestation", content: "Tu es un expert en relation client pour les prestataires culinaires. Redige un email a envoyer 24h apres une prestation de chef a domicile pour [type d'evenement]. Remercier, s'assurer de la satisfaction, demander un avis Google, et proposer de renouveler. Ton chaleureux et sincere. 8 lignes." },
  { id: "chefdom-24", category: "chef-a-domicile", title: "Post Instagram plat signature", content: "Tu es un expert en communication culinaire pour les reseaux sociaux. Redige une legende Instagram de 100 mots pour presenter mon plat signature : [nom et description du plat]. Decrire le produit, la technique, l'emotion gustative. Appel a reservation. 6 hashtags gastronomie fine. Ton poetique et appetissant." },
  { id: "chefdom-25", category: "chef-a-domicile", title: "Menu personnalise regime special", content: "Tu es un chef cuisinier expert en cuisine adaptee aux regimes speciaux. Propose un menu de [nombre de plats] entree/plat/dessert pour [regime : vegetarien / vegan / sans gluten / sans lactose] pour un diner de [nombre] personnes. Produits de saison. Chaque plat avec une courte description gourmande." },
  { id: "chefdom-26", category: "chef-a-domicile", title: "Prospection LinkedIn", content: "Tu es un expert en developpement commercial pour les chefs a domicile. Redige un message LinkedIn de premier contact pour proposer mes services a [cible : directeur d'entreprise / particulier aise / organisateur d'evenements]. Presenter la valeur unique, proposer une premiere consultation. 6 lignes. Ton elegant et direct." },
  { id: "chefdom-27", category: "chef-a-domicile", title: "Reponse a une demande personnalisee", content: "Tu es un chef a domicile expert en experiences culinaires sur-mesure. Redige un email de reponse a une demande pour [type d'occasion : anniversaire / demande en mariage / diner d'affaires]. Proposer un concept de menu adapte, expliquer le deroule, rassurer sur la logistique. Ton chaleureux et raffine." },
  { id: "chefdom-28", category: "chef-a-domicile", title: "Conditions generales de prestation", content: "Tu es un expert juridique pour les prestataires de service independants francais. Redige des conditions generales claires pour un chef a domicile. Inclus : modalites de reservation et acompte, politique d'annulation, fourniture des ingredients, responsabilite, confidentialite. Langage accessible." },
  { id: "chefdom-29", category: "chef-a-domicile", title: "Story coulisses preparation", content: "Tu es un expert en storytelling culinaire sur Instagram. Redige le texte pour une serie de 6 stories montrant les coulisses de la preparation d'un diner prive de chef a domicile. Chaque story : legende 12 mots max + une question ou accroche qui engage l'audience. Ton authentique et passionne." },
  { id: "chefdom-30", category: "chef-a-domicile", title: "FAQ pour site web", content: "Tu es un expert en experience client pour les prestataires culinaires haut de gamme. Genere une FAQ de 8 questions-reponses pour le site web d'un chef a domicile. Questions types des clients avant reservation : logistique, fournitures, tarifs, regimes speciaux, zone d'intervention. Reponses rassurantes et claires." },

  // Coach sportif independant
  { id: "coach-31", category: "coach-sportif-independant", title: "Suivi bilan decouverte client", content: "Tu es un expert en communication client pour les coachs sportifs independants. Redige un email de suivi apres un premier bilan decouverte avec [prenom]. Resumer les objectifs identifies, proposer un programme adapte, presenter les tarifs, et proposer de demarrer. Ton motivant et professionnel. 10 lignes." },
  { id: "coach-32", category: "coach-sportif-independant", title: "Programme d'entrainement personnalise", content: "Tu es un coach sportif expert en preparation physique. Redige un programme d'entrainement de [duree : 4/8/12 semaines] pour un client [profil : age, niveau, objectif]. Frequence : [X] seances par semaine. Inclus : echauffement, exercices avec series/repetitions, recuperation. Format clair et motivant." },
  { id: "coach-33", category: "coach-sportif-independant", title: "Post Instagram resultat client", content: "Tu es un expert en personal branding pour les coachs sportifs sur Instagram. Redige un post de 200 mots pour celebrer le resultat d'un client apres [duree] de coaching : [resultat obtenu]. Valoriser le travail du client, expliquer la methode, inspirer les prospects. Accroche forte, appel a l'action. 7 hashtags fitness." },
  { id: "coach-34", category: "coach-sportif-independant", title: "Reponse a une objection prix", content: "Tu es un expert en communication commerciale pour les coachs sportifs. Redige une reponse email a un prospect qui trouve le tarif de coaching trop eleve. Revaloriser l'investissement en termes de resultats, proposer une formule adaptee. Ton empathique et convaincant. 8 lignes." },
  { id: "coach-35", category: "coach-sportif-independant", title: "Relance prospect sans reponse", content: "Tu es un expert en suivi commercial pour les coachs independants. Redige un message de relance pour un prospect qui a demande des informations il y a [X] jours sans donner suite. Rappeler la valeur, lever une objection probable, proposer un appel. 4 lignes. Ton naturel et sans pression." },
  { id: "coach-36", category: "coach-sportif-independant", title: "Newsletter mensuelle clients", content: "Tu es un expert en content marketing pour les coachs sportifs. Redige une newsletter mensuelle de 300 mots pour mes clients. Structure : conseil fitness du mois / recette nutrition / motivation / offre ou actualite du coaching. Ton motivant, accessible et expert. Personnalisable avec [prenom] en intro." },
  { id: "coach-37", category: "coach-sportif-independant", title: "Description des formules coaching", content: "Tu es un expert en copywriting pour les coachs sportifs independants. Redige une description de 100 mots pour chacune de ces formules : [liste des formules et tarifs]. Chaque description doit mettre en avant le resultat attendu, le profil ideal, et ce qui est inclus. Ton motivant et oriente resultats." },
  { id: "coach-38", category: "coach-sportif-independant", title: "Plan alimentaire hebdomadaire", content: "Tu es un coach sportif expert en nutrition fonctionnelle. Redige un plan alimentaire hebdomadaire simple pour un client [profil : objectif, activite, contraintes alimentaires]. Inclus : structure des repas par jour, exemples de repas concrets, conseils d'hydratation. Ton pedagogique et encourageant." },
  { id: "coach-39", category: "coach-sportif-independant", title: "Posts motivation hebdomadaires", content: "Tu es un expert en content marketing pour les coachs sportifs sur Instagram. Redige 4 posts de motivation hebdomadaires de 80 mots chacun sur les themes suivants : [liste 4 themes]. Chaque post doit avoir une accroche forte, un conseil actionnable, et une question engageante pour les commentaires." },
  { id: "coach-40", category: "coach-sportif-independant", title: "Demande de temoignage client", content: "Tu es un expert en marketing pour les coachs sportifs independants. Redige 3 versions d'un message a envoyer a un client apres avoir atteint son objectif pour lui demander un temoignage. Versions : SMS (3 lignes) / email (6 lignes) / message vocal (script 30 secondes). Ton chaleureux et reconnaissant." },

  // Agence immobiliere
  { id: "immo-41", category: "agence-immobiliere", title: "Annonce bien difficile a vendre", content: "Tu es un expert en redaction d'annonces immobilieres. Redige une annonce de 180 mots pour un appartement de [surface]m2 au [etage] sans ascenseur, [orientation], situe a [quartier]. Points positifs : [liste]. Points negatifs a transformer : [liste]. Transformer les contraintes en opportunites, ton vendeur mais honnete." },
  { id: "immo-42", category: "agence-immobiliere", title: "Email relance apres visite", content: "Tu es un expert en suivi commercial immobilier. Redige un email de relance a envoyer 48h apres une visite de [type de bien] a [adresse] avec [prenom]. Le message doit rouvrir la conversation, proposer de repondre aux questions, et orienter vers une prochaine etape. Ton naturel et non commercial. 6 lignes." },
  { id: "immo-43", category: "agence-immobiliere", title: "Script negociation baisse de prix", content: "Tu es un agent immobilier expert en negociation. Redige un script de presentation orale de 3 minutes pour convaincre un proprietaire de baisser le prix de son bien de [X]% apres [duree] sans offre. Structure : valoriser le bien / donnees marche / impact sur la vente / proposition concrete. Ton direct mais respectueux." },
  { id: "immo-44", category: "agence-immobiliere", title: "Demande de mandat exclusif", content: "Tu es un expert en developpement commercial immobilier. Redige un email pour proposer un mandat exclusif a un proprietaire qui hesite entre plusieurs agences. Mettre en avant les avantages du mandat exclusif, notre methode de vente, notre reseau. Ton convaincant et professionnel. 10 lignes." },
  { id: "immo-45", category: "agence-immobiliere", title: "Post LinkedIn etude de marche", content: "Tu es un expert en personal branding pour les agents immobiliers sur LinkedIn. Redige un post de 200 mots presentant l'etat du marche immobilier a [ville/quartier] au [trimestre]. Donnees cles, tendances, conseil pour acheteurs et vendeurs. Ton expert, accessible, question engageante en fin de post." },
  { id: "immo-46", category: "agence-immobiliere", title: "Suivi compromis de vente", content: "Tu es un expert en communication client pour les agences immobilieres. Redige un email de suivi a envoyer a l'acheteur et au vendeur apres signature du compromis. Recapituler les prochaines etapes, rassurer sur les delais, proposer un point regulier. Versions distinctes acheteur/vendeur. Ton rassurant et structure." },
  { id: "immo-47", category: "agence-immobiliere", title: "Reponse a un avis negatif", content: "Tu es un expert en gestion de reputation pour les agences immobilieres. Redige une reponse a cet avis Google : [colle l'avis]. 5 lignes maximum. Reconnaitre l'experience sans admettre de faute, expliquer le contexte si pertinent, proposer un contact direct. Ton professionnel et calme." },
  { id: "immo-48", category: "agence-immobiliere", title: "Newsletter acquereurs", content: "Tu es un expert en content marketing immobilier. Redige une newsletter mensuelle de 300 mots pour mes clients acquereurs en recherche active. Structure : nouveautes du marche local / bien coup de coeur du mois / conseil pratique (financement / DPE / negociation) / invitation a prendre RDV. Ton expert et utile." },
  { id: "immo-49", category: "agence-immobiliere", title: "Presentation de l'agence", content: "Tu es un expert en copywriting pour les agences immobilieres independantes. Redige une presentation de 200 mots de notre agence pour la page A propos du site. Mettre en avant : anciennete, specialite, zone geographique, approche humaine, resultats. Ton professionnel, chaleureux et differenciant." },
  { id: "immo-50", category: "agence-immobiliere", title: "SMS confirmation de visite", content: "Tu es un expert en relation client pour les agences immobilieres. Redige un SMS de confirmation de visite pour [prenom] pour le bien situe [adresse] le [date] a [heure]. Inclure le code d'acces si necessaire, un numero de contact en cas d'imprevu. 3 lignes. Ton professionnel et efficace." },

  // Journaliste independant (v3)
  { id: "v3-01", category: "journaliste-independant", title: "Pitch article a une redaction", content: "Tu es un expert en communication editoriale pour les journalistes independants. Redige un pitch d'article de 150 mots a envoyer a un redacteur en chef sur le sujet suivant : [sujet]. Inclus : angle choisi, pourquoi c'est pertinent maintenant, sources envisagees, format propose (reportage / enquete / portrait / analyse), delai de livraison. Ton professionnel et accrocheur." },
  { id: "v3-02", category: "journaliste-independant", title: "Relance redacteur sans reponse", content: "Tu es un expert en communication professionnelle pour les journalistes freelance. Redige un email de relance pour un pitch envoye il y a [X] jours sans reponse a [nom de la redaction]. Rappeler l'angle, souligner l'actualite du sujet, proposer d'ajuster si besoin. Ton direct et respectueux. 5 lignes." },
  { id: "v3-03", category: "journaliste-independant", title: "Demande d'interview a une source", content: "Tu es un expert en communication journalistique. Redige un email de demande d'interview pour [nom / fonction de la personne] dans le cadre d'un article sur [sujet] destine a [media]. Presenter le cadre de l'article, le type de questions envisagees, et les modalites (duree, format, delai). Ton professionnel et respectueux." },
  { id: "v3-04", category: "journaliste-independant", title: "Resume article pour reseaux sociaux", content: "Tu es un expert en distribution de contenu editorial sur les reseaux sociaux. Redige 3 versions de publication pour promouvoir cet article : [titre et resume]. Version LinkedIn (200 mots, ton expert), version Twitter/X (280 caracteres, accroche forte), version Instagram (caption 100 mots + 5 hashtags). Chaque version avec un angle different." },
  { id: "v3-05", category: "journaliste-independant", title: "Presentation de l'offre freelance", content: "Tu es un expert en copywriting pour les journalistes independants. Redige une page de presentation de 250 mots pour mon activite de journaliste freelance. Specialites : [thematiques]. Medias clients : [liste]. Formats maitrises : [liste]. Public cible : [type de redaction]. Ton credible, concis et differenciant." },
  { id: "v3-06", category: "journaliste-independant", title: "Compte-rendu de conference", content: "Tu es un journaliste expert en synthese d'evenements professionnels. Redige un compte-rendu de 400 mots d'une conference sur [theme] qui s'est tenue le [date] a [lieu]. Intervenants : [liste]. Points cles abordes : [liste]. Ton informatif, factuel et accessible a un public non-specialiste." },
  { id: "v3-07", category: "journaliste-independant", title: "Newsletter thematique", content: "Tu es un expert en content marketing editorial. Redige une newsletter hebdomadaire de 350 mots sur [thematique] pour une audience de [profil de lecteurs]. Structure : accroche d'actualite / 3 informations a retenir / une ressource recommandee / une question pour susciter la reflexion. Ton expert, accessible et engageant." },
  { id: "v3-08", category: "journaliste-independant", title: "Profil LinkedIn journaliste", content: "Tu es un expert en personal branding pour les journalistes independants. Redige la section Infos du profil LinkedIn d'un journaliste freelance specialise en [thematiques]. Mettre en avant : expertise, medias clients, approche editoriale, disponibilite pour nouvelles missions. 300 mots. Ton professionnel et authentique." },
  { id: "v3-09", category: "journaliste-independant", title: "Reponse a une demande de correction", content: "Tu es un expert en communication professionnelle pour les journalistes. Redige un email de reponse a un redacteur en chef qui demande des modifications sur un article livre. Reconnaitre le retour, proposer les modifications ou un point de discussion si desaccord editorial, confirmer le nouveau delai. Ton professionnel et constructif." },
  { id: "v3-10", category: "journaliste-independant", title: "Demande de droits de republication", content: "Tu es un expert en droits editoriaux pour les journalistes independants. Redige un email pour demander a [nom du media] l'autorisation de republier ou d'adapter un article ecrit pour eux sur [sujet]. Preciser l'usage envisage, le support, et proposer une compensation si necessaire. Ton professionnel et direct." },

  // Courtier en credit (v3)
  { id: "v3-11", category: "courtier-credit", title: "Premier contact prospect", content: "Tu es un expert en communication commerciale pour les courtiers en credit immobilier. Redige un email de premier contact pour un prospect qui a rempli un formulaire sur [type de projet : achat residence principale / investissement locatif / renegociation]. Presenter l'offre de service, rassurer sur la demarche, proposer un RDV telephonique. Ton professionnel et rassurant. 8 lignes." },
  { id: "v3-12", category: "courtier-credit", title: "Suivi apres rendez-vous decouverte", content: "Tu es un expert en relation client pour les courtiers independants. Redige un email de suivi apres un premier rendez-vous avec [prenom], qui souhaite financer [type de projet] a hauteur de [montant]. Recapituler les elements cles recueillis, les prochaines etapes du dossier, et les documents a fournir. Ton rassurant et structure." },
  { id: "v3-13", category: "courtier-credit", title: "Relance dossier en attente de documents", content: "Tu es un expert en communication client pour les courtiers en credit. Redige un email de relance pour un client dont le dossier attend les documents suivants : [liste des documents manquants]. Expliquer l'importance de ces pieces pour avancer, proposer de l'aide si besoin. Ton patient et pedagogique. 6 lignes." },
  { id: "v3-14", category: "courtier-credit", title: "Annonce d'une offre de pret obtenue", content: "Tu es un expert en communication pour les intermediaires bancaires. Redige un email pour annoncer a [prenom] l'obtention d'une offre de pret de [montant] sur [duree] au taux de [taux]%. Presenter les conditions obtenues, expliquer les prochaines etapes (signature, deblocage), et feliciter. Ton enthousiaste et professionnel." },
  { id: "v3-15", category: "courtier-credit", title: "Explication du role du courtier", content: "Tu es un expert en pedagogie financiere pour les courtiers en credit. Redige un texte de 200 mots expliquant simplement le role d'un courtier en credit immobilier a un primo-accedant. Mettre en avant la valeur ajoutee, la gratuite pour le client, et les differences avec une demarche bancaire directe. Ton clair et rassurant." },
  { id: "v3-16", category: "courtier-credit", title: "Post LinkedIn positionnement", content: "Tu es un expert en personal branding pour les courtiers en credit. Redige un post LinkedIn de 200 mots sur le theme : [ex : erreurs a eviter lors d'une demande de credit / comment bien preparer son dossier / comprendre le taux d'endettement]. Ton expert, accessible, accroche forte, question engageante en fin." },
  { id: "v3-17", category: "courtier-credit", title: "Reponse a un refus bancaire", content: "Tu es un expert en communication pour les courtiers en credit. Redige un email pour expliquer a [prenom] que sa demande a ete refusee par [banque] et presenter les alternatives envisageables (autre banque, co-emprunteur, apport complementaire, delai de quelques mois). Ton empathique, constructif et oriente solutions. 10 lignes." },
  { id: "v3-18", category: "courtier-credit", title: "Demande de temoignage apres obtention", content: "Tu es un expert en marketing pour les courtiers independants. Redige 3 versions d'un message a envoyer a un client dont le pret vient d'etre debloque pour lui demander un avis Google ou temoignage LinkedIn. Versions : SMS (3 lignes) / email (5 lignes) / WhatsApp (naturel, 2 lignes). Ton chaleureux et reconnaissant." },
  { id: "v3-19", category: "courtier-credit", title: "Newsletter mensuelle prospects", content: "Tu es un expert en content marketing pour les courtiers en credit immobilier. Redige une newsletter mensuelle de 300 mots pour des prospects en phase de reflexion. Structure : point sur les taux du moment / conseil pratique du mois / idee recue demystifiee / invitation a un RDV gratuit. Ton expert, accessible et utile." },
  { id: "v3-20", category: "courtier-credit", title: "Presentation de l'offre de service", content: "Tu es un expert en copywriting pour les courtiers en credit independants. Redige une page de presentation de 200 mots pour mon activite de courtier. Zones couvertes : [liste]. Types de projets accompagnes : [liste]. Valeur ajoutee par rapport a une demarche directe en banque. Ton professionnel, rassurant et oriente resultats." },

  // Marchand de biens (v3)
  { id: "v3-21", category: "marchand-de-biens", title: "Offre d'achat argumentee", content: "Tu es un expert en negociation immobiliere pour les marchands de biens. Redige une lettre d'offre d'achat pour un bien situe [adresse] propose a [prix demande]. Prix offert : [prix]. Arguments justifiant la decote : [travaux estimes / DPE / localisation / duree sur le marche]. Ton professionnel, factuel et convaincant. 1 page." },
  { id: "v3-22", category: "marchand-de-biens", title: "Presentation d'un projet a un investisseur", content: "Tu es un expert en communication financiere pour les marchands de biens. Redige une note de presentation d'une page pour un projet d'acquisition-renovation-revente de [type de bien] a [ville]. Inclus : prix d'acquisition, budget travaux estime, prix de revente cible, marge brute estimee, delai previsionnel. Ton professionnel et oriente rentabilite." },
  { id: "v3-23", category: "marchand-de-biens", title: "Email a un notaire pour accelerer un dossier", content: "Tu es un expert en communication professionnelle dans l'immobilier. Redige un email a envoyer a un notaire pour faire avancer un dossier de [type d'acte] sur le bien situe [adresse]. Rappeler les elements deja transmis, les points en attente, et exprimer l'urgence de facon ferme mais respectueuse. 6 lignes." },
  { id: "v3-24", category: "marchand-de-biens", title: "Annonce de revente renovee", content: "Tu es un expert en redaction d'annonces immobilieres premium. Redige une annonce de 200 mots pour la revente d'un [type de bien] entierement renove de [surface]m2 situe a [ville/quartier]. Travaux realises : [liste]. Points forts : [liste]. Public cible : [acquereur type]. Ton vendeur, honnete et valorisant." },
  { id: "v3-25", category: "marchand-de-biens", title: "Reponse a un syndic ou copropriete", content: "Tu es un expert en communication pour les operateurs immobiliers. Redige un email de reponse a une demande ou contestation du syndic concernant [sujet : travaux / assemblee generale / charges]. Ton ferme, factuel et professionnel. Proposer une resolution concrete. 8 lignes." },
  { id: "v3-26", category: "marchand-de-biens", title: "Demande de financement bancaire", content: "Tu es un expert en communication financiere pour les marchands de biens. Redige un email a envoyer a un directeur d'agence bancaire pour presenter un projet d'acquisition-renovation et solliciter un financement court terme. Inclus : description du projet, prix d'achat, travaux, valeur de revente, experience de l'operateur. Ton professionnel et structure." },
  { id: "v3-27", category: "marchand-de-biens", title: "Mise en demeure entreprise de travaux", content: "Tu es un expert juridique pour les maitres d'ouvrage. Redige une lettre de mise en demeure a envoyer a une entreprise de travaux qui n'a pas respecte le delai ou la qualite convenus sur le chantier situe [adresse]. Rappeler les obligations contractuelles, les manquements constates, et le delai pour regulariser avant recours. Ton ferme et legal." },
  { id: "v3-28", category: "marchand-de-biens", title: "Bilan operation post-revente", content: "Tu es un expert en gestion de projets immobiliers. Redige un bilan synthetique d'une operation marchand de biens : acquisition a [prix], travaux [montant], frais [montant], prix de revente [prix], duree [mois]. Presenter le resultat net, la marge, le ROI, et les enseignements pour les prochaines operations. Format tableau + commentaire 100 mots." },
  { id: "v3-29", category: "marchand-de-biens", title: "Post LinkedIn retour d'experience", content: "Tu es un expert en personal branding pour les marchands de biens sur LinkedIn. Redige un post de 200 mots presentant le retour d'experience d'une operation d'acquisition-renovation-revente a [ville]. Type de bien, travaux realises, resultat, enseignement cle. Ton expert, authentique, accroche forte, question engageante." },
  { id: "v3-30", category: "marchand-de-biens", title: "Email reseau pour sourcing off-market", content: "Tu es un expert en developpement de reseau pour les operateurs immobiliers. Redige un email a envoyer a des notaires, agents immobiliers ou gestionnaires de patrimoine pour signaler mon activite de marchand de biens et mes criteres d'acquisition : [zone geographique, budget, type de biens, etat recherche]. Ton professionnel et direct. 8 lignes." },

  // Conciergerie location courte duree (v3)
  { id: "v3-31", category: "conciergerie-lcd", title: "Message de bienvenue voyageur", content: "Tu es un expert en hospitalite pour les conciergeries de location courte duree. Redige un message de bienvenue a envoyer au voyageur le jour de son arrivee dans le logement situe [adresse]. Inclus : code d'acces ou instructions d'entree, points essentiels du logement, contact en cas de probleme, recommandations locales. Ton chaleureux et professionnel. 15 lignes maximum." },
  { id: "v3-32", category: "conciergerie-lcd", title: "Reponse a un avis negatif Airbnb", content: "Tu es un expert en gestion de reputation pour les conciergeries Airbnb. Redige une reponse publique a cet avis negatif : [colle l'avis]. 5 lignes maximum. Reconnaitre l'experience, expliquer sans se justifier excessivement, montrer les mesures prises. Ton calme, professionnel et constructif." },
  { id: "v3-33", category: "conciergerie-lcd", title: "Message de depart et retour caution", content: "Tu es un expert en relation client pour les gestionnaires de locations courtes durees. Redige un message a envoyer le jour du depart du voyageur. Rappeler l'heure de check-out, les instructions de depart (menage, cles, etc.), et annoncer le deblocage de la caution sous [X] jours si tout est conforme. Ton chaleureux et clair." },
  { id: "v3-34", category: "conciergerie-lcd", title: "Proposition de service aux proprietaires", content: "Tu es un expert en developpement commercial pour les conciergeries de location courte duree. Redige un email de prospection a envoyer a un proprietaire d'un bien idealement situe pour la LCD. Presenter les services, la valeur ajoutee, les tarifs de commission, et les resultats attendus en termes de taux d'occupation et revenus. Ton professionnel et convaincant. 10 lignes." },
  { id: "v3-35", category: "conciergerie-lcd", title: "Guide d'accueil du logement", content: "Tu es un expert en hospitalite pour les conciergeries Airbnb. Redige un guide d'accueil complet pour un appartement de [type] situe a [ville/quartier]. Sections a inclure : equipements disponibles, regles du logement, acces wifi, gestion des dechets, stationnement, transports, restaurants et commerces recommandes a proximite. Ton chaleureux et pratique." },
  { id: "v3-36", category: "conciergerie-lcd", title: "Relance proprietaire inactif", content: "Tu es un expert en fidelisation client pour les conciergeries. Redige un email a envoyer a un proprietaire partenaire dont le bien n'est plus actif depuis [X] mois. Rappeler la valeur du partenariat, proposer un point pour reevaluer la strategie, partager les performances actuelles du marche local. Ton proactif et chaleureux. 6 lignes." },
  { id: "v3-37", category: "conciergerie-lcd", title: "Gestion d'une reclamation voyageur", content: "Tu es un expert en gestion des litiges pour les conciergeries de location courte duree. Redige un message de reponse a un voyageur qui signale un probleme dans le logement pendant son sejour : [description du probleme]. Reconnaitre la gene, proposer une solution immediate, et si necessaire un geste commercial. Ton reactif et professionnel." },
  { id: "v3-38", category: "conciergerie-lcd", title: "Rapport mensuel pour le proprietaire", content: "Tu es un expert en communication pour les gestionnaires de biens en location courte duree. Redige un email de rapport mensuel pour un proprietaire partenaire. Inclus : nombre de nuits louees, taux d'occupation, revenus generes, commission deduite, net verse, avis voyageurs du mois, actions prises ou a prevoir. Ton transparent et professionnel." },
  { id: "v3-39", category: "conciergerie-lcd", title: "Post Instagram logement disponible", content: "Tu es un expert en communication pour les conciergeries Airbnb sur Instagram. Redige une legende de 100 mots pour presenter un appartement disponible a la location courte duree a [ville]. Type de bien : [description]. Points forts : [liste]. Periode de disponibilite : [dates]. Inclure un appel a reserver et 6 hashtags pertinents voyage/location." },
  { id: "v3-40", category: "conciergerie-lcd", title: "Reglement interieur du logement", content: "Tu es un expert en hospitalite et gestion locative. Redige un reglement interieur clair et complet pour un logement en location courte duree a [ville]. Inclus : horaires check-in/check-out, regles de bruit, interdictions (fetes, tabac, animaux), nombre maximum d'occupants, gestion des dechets, consequences en cas de non-respect. Ton ferme mais accueillant." },

  // Maitre d'oeuvre BTP (v3)
  { id: "v3-41", category: "maitre-oeuvre-btp", title: "Reponse a une demande de devis", content: "Tu es un expert en communication commerciale pour les maitres d'oeuvre independants. Redige un email de reponse a une demande de devis pour une mission de maitrise d'oeuvre sur un projet de [type de travaux] d'un budget estime a [montant] a [ville]. Presenter la demarche, les etapes de la mission, les honoraires indicatifs et proposer un RDV de visite. Ton professionnel et rassurant. 10 lignes." },
  { id: "v3-42", category: "maitre-oeuvre-btp", title: "Compte-rendu de reunion de chantier", content: "Tu es un expert en communication de chantier pour les maitres d'oeuvre. Redige un compte-rendu de reunion de chantier du [date] pour le projet [nom] situe [adresse]. Presents : [liste]. Points abordes : [liste]. Decisions prises : [liste]. Actions a mener avant la prochaine reunion : [liste avec responsable et delai]. Ton structure et factuel." },
  { id: "v3-43", category: "maitre-oeuvre-btp", title: "Mise en demeure entreprise defaillante", content: "Tu es un expert juridique pour les maitres d'oeuvre BTP. Redige une lettre de mise en demeure a envoyer a l'entreprise [nom] qui n'a pas respecte [le delai / la qualite / le planning] sur le chantier [adresse]. Rappeler les obligations contractuelles, les manquements constates avec dates, et le delai pour regulariser avant penalites ou resiliation. Ton ferme et legal." },
  { id: "v3-44", category: "maitre-oeuvre-btp", title: "Email de presentation a un client", content: "Tu es un expert en copywriting pour les maitres d'oeuvre independants. Redige un email de presentation de mon activite a un particulier qui envisage une renovation de [type]. Expliquer le role du maitre d'oeuvre, la valeur ajoutee, les honoraires habituels, et proposer un RDV de decouverte. Ton clair et rassurant. 10 lignes." },
  { id: "v3-45", category: "maitre-oeuvre-btp", title: "Rapport d'avancement mensuel", content: "Tu es un expert en communication de projet pour les maitres d'oeuvre. Redige un rapport d'avancement mensuel pour le mois de [mois] sur le chantier [nom]. Inclus : travaux realises, avancement vs planning, points de blocage, travaux prevus le mois suivant, etat financier (engage vs budget), points d'attention pour le client. Format clair et structure." },
  { id: "v3-46", category: "maitre-oeuvre-btp", title: "Reponse a un retard de chantier", content: "Tu es un expert en communication de crise pour les professionnels du BTP. Redige un email a envoyer a un client pour l'informer d'un retard de [duree] sur son chantier du a [cause : intemperies / retard materiaux / sous-traitant defaillant]. Expliquer clairement, proposer le nouveau planning, rassurer sur la qualite finale. Ton transparent et professionnel." },
  { id: "v3-47", category: "maitre-oeuvre-btp", title: "Consultation d'entreprises pour appel d'offres", content: "Tu es un expert en gestion de projet BTP. Redige un email de consultation a envoyer a [X] entreprises pour solliciter leurs offres sur le lot [nom du lot] du chantier [adresse]. Inclus : description des travaux, plans joints, delai de reponse, criteres de selection, date de debut prevue. Ton professionnel et precis." },
  { id: "v3-48", category: "maitre-oeuvre-btp", title: "Post LinkedIn chantier livre", content: "Tu es un expert en personal branding pour les maitres d'oeuvre independants. Redige un post LinkedIn de 200 mots presentant un chantier recemment livre. Type de projet : [description]. Surface : [X]m2. Duree : [X] mois. Principaux corps de metier coordonnes. Resultat pour le client. Ton expert, factuel et accessible. Accroche forte, question finale." },
  { id: "v3-49", category: "maitre-oeuvre-btp", title: "Reclamation aupres d'un assureur", content: "Tu es un expert en communication technique pour les professionnels du BTP. Redige un email de declaration de sinistre ou de reclamation aupres de l'assurance decennale pour [type de desordre constate] sur le chantier [adresse], livre le [date]. Decrire les faits precisement, joindre les preuves disponibles, demander l'ouverture d'un dossier. Ton factuel et structure." },
  { id: "v3-50", category: "maitre-oeuvre-btp", title: "Email remise de chantier au client", content: "Tu es un expert en relation client pour les maitres d'oeuvre. Redige un email d'accompagnement de la remise de chantier a [prenom client] pour le projet [type] livre le [date]. Inclus : felicitations, rappel des garanties legales (parfait achevement, biennale, decennale), contacts des entreprises, conseils d'entretien, et disponibilite pour la suite. Ton chaleureux et professionnel." },

  // Bibliotheque strategique v4 (150 prompts, memes 15 metiers)
  ...STRATEGIC_V4_PROMPTS,
];
